blog/urls.py
from django.urls import path

from .feeds import UltimosPostsFeed
from . import views


app_name = 'blog'

urlpatterns = [
    path('<int:post_id>/compartilhar-post/', views.compartilhar_post, name='compartilhar_post'),
    path('<int:ano>/<int:mes>/<int:dia>/<slug:post>/', views.detalhe_post, name='detalhe_post'),
    path('tag/<slug:tag_slug>/', views.lista_post, name='listar_post_by_tag'),
    path('feed/', UltimosPostsFeed(), name='post_feed'),
    path('post-buscar/', views.post_buscar, name='post_buscar'),
    path('', views.lista_post, name='listar_posts'),
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.db import models

from taggit.managers import TaggableManager


class PublicadasManager(models.Manager):
    def get_queryset(self):
        return super(PublicadasManager, self).get_queryset().filter(status='publicadas')


class Post(models.Model):
    STATUS_CHOICES = (
        ('rascunho', 'Rascunho'),
        ('publicadas', 'Publicadas'),
    )

    titulo = models.CharField(max_length=250, null=True, blank=True)
    slug = models.SlugField(max_length=250, unique_for_date='publicada')
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    corpo = models.TextField()
    publicada = models.DateField(default=timezone.now)
    criada = models.DateTimeField(auto_now_add=True)
    atualizada = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='rascunho')
    objetos = models.Manager()
    publicadas = PublicadasManager()
    tags = TaggableManager()

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ('-publicada',)
        db_table = 'post'

    def get_absolute_url(self):
        return reverse(
            'blog:detalhe_post',
            args=[
                self.publicada.year,
                self.publicada.month,
                self.publicada.day,
                self.slug
            ]
        )

    def __str__(self):
        return f'{self.titulo}'


class Comentario(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comentario')
    nome = models.CharField(max_length=80)
    email = models.EmailField()
    corpo = models.TextField()
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)
    ativo = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'
        ordering = ('-criado',)
        db_table = 'comentarios'

blog/forms.py
from django import forms
from .models import Comentario


class EmailPostForm(forms.Form):
    nome = forms.CharField(max_length=150)
    email_destino = forms.EmailField()
    comentario = forms.CharField(required=False, widget=forms.Textarea)


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = (
            'nome',
            'email',
            'corpo'
        )


class BuscarForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag

from .forms import EmailPostForm, ComentarioForm, BuscarForm
from .models import Post


# class PostListView(ListView):
#     queryset = Post.publicadas.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/posts.html'


def lista_post(request, tag_slug=None):
    object_list = Post.publicadas.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'page': page, 'posts': posts, 'tag': tag}

    return render(request, 'blog/post/posts.html', context)


def detalhe_post(request, ano, mes, dia, post):
    template = 'blog/post/detalhe_post.html'
    post = get_object_or_404(
        Post,
        slug=post,
        status='publicadas',
        publicada__year=ano,
        publicada__month=mes,
        publicada__day=dia
    )

    comentarios = post.comentario.filter(ativo=True)
    novo_comentario = None

    posts_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.publicadas.filter(tags__in=posts_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'publicada')[:4]

    if request.method == 'POST':
        comentario_form = ComentarioForm(data=request.POST)
        if comentario_form.is_valid():
            novo_comentario = comentario_form.save(commit=False)
            novo_comentario.post = post
            novo_comentario.save()
    else:
        comentario_form = ComentarioForm()

    context = {
        'post': post,
        'comentarios': comentarios,
        'novo_comentario': novo_comentario,
        'comentario_form': comentario_form,
        'similar_posts': similar_posts
    }

    return render(request, template, context)


def compartilhar_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='publicadas')
    template = 'blog/post/enviar_post.html'
    enviado = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            formulario_submetido = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            mensagem_cabecalho = f'{formulario_submetido["nome"]} recomenda você ler {post.titulo}'
            mensagem = f'Ler {post.titulo} no {post_url} \n\n {formulario_submetido["nome"]}' \
                       f' s comentario: {formulario_submetido["comentario"]}'

            send_mail(
                mensagem_cabecalho,
                mensagem,
                'samueldjangoex42@gmail.com',
                [formulario_submetido['email_destino']]
            )
            enviado = True
    else:
        form = EmailPostForm()

    context = {'post': post, 'form': form, 'enviado': enviado}

    return render(request, template, context)


def post_buscar(request):
    form = BuscarForm()
    query = None
    resultados = list()

    if 'query' in request.GET:
        form = BuscarForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('titulo', weight='A') + SearchVector('corpo', weight='B')
            search_quey = SearchQuery(query)
            resultados = Post.publicadas.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_quey)
            ).filter(rank__gte=0.3).order_by('-rank')

    context = {
        'form': form,
        'query': query,
        'resultados': resultados
    }

    return render(request, 'blog/post/buscar.html', context)

blog/templates/blog/post/buscar.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load bootstrap %}

{% block title %} Buscar {% endblock %}
{% block link %}
    <link href="{% static 'css/blog.css' %}" type="text/css" rel="stylesheet" media="screen,projection">
{% endblock %}

{% block content %}

    {% if query %}
        <h2>Posts que contêm {{ query }}</h2>
        <h3>
            {% with resultados.count as total_posts %}
                Encontrados {{ total_posts }} resultados{{ total_posts|pluralize }}
            {% endwith %}
        </h3>
        {% for post in resultados %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.titulo }}</a>
            </h4>
            {{ post.corpo|markdown|truncatechars_html:5 }}
        {% endfor %}
        <a href="{% url 'blog:post_buscar' %}">
            Buscar novamente
        </a>
    {% else %}
        <h3>Buscar posts</h3>
        <form method="GET">
            {{ form|bootstrap }}
            <button class="btn btn-primary" type="submit">
                Buscar
            </button>
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/detalhe_post.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load bootstrap %}

{% block title %} {{ post.titulo }} {% endblock %}
{% block link %}
    <link href="{% static 'css/blog.css' %}" type="text/css" rel="stylesheet" media="screen,projection">
{% endblock %}

{% block content %}
     <div class="card p-3 mt-1">
        <h3>Publicação similares</h3>
        {% for post in similar_posts %}
            <a href="{{ post.get_absolute_url }}">{{ post.titulo }}</a>
        {% empty %}
            Não há postagens simiulares
        {% endfor %}
     </div>

    <div class="card p-3 mt-3">
        <h3 class="date">
            Publicação {{ post.publicada }} by {{ post.autor }}
        </h3>
        {{ post.corpo|markdown }}
        {% with comentarios.count as total_comentarios %}
            <h4>
                {{ total_comentarios }} comentário{{ total_comentarios|pluralize }}
            </h4>
        {% endwith %}
    </div>

    {% if novo_comentario %}
        <div class="alert alert-success mt-3 mb-3">
            <h3>Comentário adicionado com sucesso!</h3>
        </div>
    {% else %}
        <div class="card p-3 mt-3 mb-3 rounded">
            <h3>Adicionar comentário</h3>
            <form method="POST"> {% csrf_token %}
                {{ comentario_form|bootstrap }}
                <button class="btn btn-primary mt-3" type="submit">
                    Enviar Comentário
                </button>
            </form>
        </div>
    {% endif %}

    {% for comentario in comentarios %}
        <div class="card p-3 mt-3 mb-3 rounded">
            <p>
                Comentário {{ forloop.counter }} by {{ comentario.nome }}
            </p>
            {{ comentario.corpo|markdown }}
        </div>
            {% empty %}
            <div class="card p-3 mt-1 mb-3 shadow rounded">
                <p>
                    Ainda não há comentário
                </p>
            </div>
    {% endfor %}

{% endblock %}

blog/templates/blog/post/enviar_post.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %} Meu Blog {% endblock %}
{% block link %}
    <link href="{% static 'css/blog.css' %}" type="text/css" rel="stylesheet" media="screen,projection">
{% endblock %}

{% block content %}
    {% if enviado %}
        <div class="card p-3 rounded mb-4 mt-2">
            <h3>E-mail enviado com sucesso!</h3>
            <p>
                "{{ post.titulo }}" formulário enviado {{ form.cleaned_data.email_destino }}
            </p>
        </div>
    {% else %}
        <div class="card p-3 rounded mb-4 mt-2">
            <h3>Compartilhar "{{ post.titulo }}" por email</h3>
            <form method="POST"> {% csrf_token %}
                {{ form|bootstrap }}
                <button class="btn btn-primary mt-3" type="submit">
                    Enviar E-mail
                </button>
            </form>
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/post/posts.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block title %} Meu Blog {% endblock %}
{% block link %}
    <link href="{% static 'css/blog.css' %}" type="text/css" rel="stylesheet" media="screen,projection">
{% endblock %}

{% block content %}
    {% if tag %}
        <h2 class="card text-xl-center p-2 mt-1">
            Posts com a tag: {{ tag.name }}
        </h2>
    {% endif %}

    {% for post in posts %}
            <div class="card p-3 mt-1">
                <a href="{{ post.get_absolute_url }}">
                    <h3>
                        {{ post.titulo }}
                    </h3>
                </a>
                <p class="tags">
                    Tags: {% for tag in post.tags.all %}
                        <a href="{% url 'blog:listar_post_by_tag' tag.slug %}">
                            {{ tag.name }}
                        </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p class="date">
                    Publicação {{ post.publicada }} by {{ post.autor }}
                </p>
                {{ post.corpo|markdown|truncatechars_html:30 }}

                <a href="{% url 'blog:compartilhar_post' post.id %}">
                    <button class="btn btn-primary">
                        Compartilhar
                    </button>
                </a>

            </div>
    {% endfor %}
    {% include "paginacao.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/ultimos_posts.html
<ul>
    {% for post in ultimos_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ post.titulo }}
            </a>
        </li>
    {% endfor %}
</ul>

templates/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="{% static 'css/blog.css' %}" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static 'css/bootstrap.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection">
    <title>{% block title %} {% endblock %}</title>
    {% block link %} {% endblock %}
</head>
<body>

<nav class="navbar navbar-dark bg-white">
    <div class="container-fluid">
        <a href="{% url 'blog:listar_posts' %}" class="navbar-brand">
            Blog do Samuel
        </a>
        <button class="btn btn-primary" type="submit">
            Post {% total_posts %}
        </button>
    </div>
</nav>

<div class="container mt-4" id="content">
    <div class="row">
        <div class="col-4 card mt-1 mb-3">
            <h2 class="mt-4">Ultimos Posts</h2>
            {% ver_ultimos_posts %}
            <h2 class="mt-4">Posts mais comentados</h2>
            {% posts_mais_comentados as posts_mais %}
            <ul>
                {% for post in posts_mais %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.titulo }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-8">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

</body>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

templates/paginacao.html
<ul class="pagination d-flex justify-content-center mt-3">
    {% if page.has_previous %}
    <li class="page-item active">
        <a class="page-link" href="?page={{ page.previous_page_number }}">Anterior</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">Anterior</a>
    </li>
    {% endif %} {% for object in page.paginator.page_range %}
    <li class="page-item waves-effect">
        <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
    </li>
    {% endfor %}{% if page.has_next %}
    <li class="page-item waves-effect active">
        <a class="page-link" href="?page={{ page.next_page_number }}">Próximo</a>
    </li>
    {% else %}
    <li class="page-item waves-effect disabled">
        <a class="page-link" href="#">Próximo</a>
    </li>
    {% endif %}
</ul>